/**
 * Generates ServiceNow SDK TypeScript code from a parsed flow/subflow structure.
 *
 * The generated code uses the official @servicenow/sdk/automation API:
 *   Flow(config, wfa.trigger(...), body)
 *   Subflow(config, body)
 *   Action(config, body)
 *
 * Deploy with: snc deploy  (ServiceNow CLI)
 * Docs: https://servicenow.github.io/sdk/
 */

export class FlowSdkCodegen {

  // ─── Main entry point ──────────────────────────────────────────────────────

  generate(flowStructure, snTableName, fieldMappings = {}) {
    const isSubflow = this._isSubflow(flowStructure);
    if (isSubflow) return this.generateSubflow(flowStructure, snTableName, fieldMappings);
    return this.generateFlow(flowStructure, snTableName, fieldMappings);
  }

  generateFlow(flowStructure, snTableName, fieldMappings = {}) {
    const internalName = this._toId(flowStructure.apiName);
    const triggerCode  = this._buildTrigger(flowStructure, snTableName);
    const bodyCode     = this._buildBody(flowStructure.elements ?? [], fieldMappings, snTableName, 'flow');
    const varCode      = this._buildFlowVariables(flowStructure.variables ?? []);

    return this._wrap(`
import { Flow, wfa, trigger, action } from '@servicenow/sdk/automation';
import { StringColumn, BooleanColumn, IntegerColumn, ReferenceColumn, DateTimeColumn } from '@servicenow/sdk/core';
import { Now } from '@servicenow/sdk';

/**
 * Migrated flow: ${flowStructure.label ?? flowStructure.apiName}
 * Source: ${flowStructure._sourcePlatform ?? 'Jira / Salesforce'}
 * Generated by SN Migration Agent
 */
export const ${internalName} = Flow(
  {
    $id: Now.ID['${internalName}'],
    name: ${JSON.stringify(flowStructure.label ?? flowStructure.apiName)},
    description: ${JSON.stringify(flowStructure.description ?? `Migrated from ${flowStructure._sourcePlatform ?? 'source platform'}`)},
    runAs: 'system',${varCode ? `\n    flowVariables: {\n${varCode}\n    },` : ''}
  },
  ${triggerCode},
  (params) => {
${bodyCode}
  }
);
`);
  }

  generateSubflow(flowStructure, snTableName, fieldMappings = {}) {
    const internalName = this._toId(flowStructure.apiName);
    const inputsCode   = this._buildInputOutputSchema(flowStructure.variables?.filter(v => v.isInput) ?? []);
    const outputsCode  = this._buildInputOutputSchema(flowStructure.variables?.filter(v => v.isOutput) ?? []);
    const bodyCode     = this._buildBody(flowStructure.elements ?? [], fieldMappings, snTableName, 'subflow');

    return this._wrap(`
import { Subflow, wfa, action } from '@servicenow/sdk/automation';
import { StringColumn, BooleanColumn, IntegerColumn, ReferenceColumn } from '@servicenow/sdk/core';
import { Now } from '@servicenow/sdk';

/**
 * Migrated subflow: ${flowStructure.label ?? flowStructure.apiName}
 * Subflows have no trigger — invoke with wfa.subflow(${internalName}, ...) from a parent flow.
 */
export const ${internalName} = Subflow(
  {
    $id: Now.ID['${internalName}'],
    name: ${JSON.stringify(flowStructure.label ?? flowStructure.apiName)},
    description: ${JSON.stringify(flowStructure.description ?? `Migrated subflow`)},
    runAs: 'system',${inputsCode ? `\n    inputs: {\n${inputsCode}\n    },` : ''}${outputsCode ? `\n    outputs: {\n${outputsCode}\n    },` : ''}
  },
  (params) => {
${bodyCode}
  }
);
`);
  }

  generateCustomAction(name, description, inputs, outputs, script) {
    const internalName = this._toId(name);
    const inputsCode   = this._buildInputOutputSchema(inputs ?? []);
    const outputsCode  = this._buildInputOutputSchema(outputs ?? []);
    const scriptEscaped = (script ?? '// TODO: implement action logic').replace(/`/g, '\\`');

    return this._wrap(`
import { Action, wfa } from '@servicenow/sdk/automation';
import { StringColumn, BooleanColumn, IntegerColumn } from '@servicenow/sdk/core';
import { Now } from '@servicenow/sdk';

/**
 * Custom Action: ${name}
 * Use in flows: wfa.action(${internalName}, { $id: Now.ID['step_id'] }, { ...inputs })
 */
export const ${internalName} = Action(
  {
    $id: Now.ID['${internalName}'],
    name: ${JSON.stringify(name)},
    description: ${JSON.stringify(description ?? '')},
    access: 'public',${inputsCode ? `\n    inputs: {\n${inputsCode}\n    },` : ''}${outputsCode ? `\n    outputs: {\n${outputsCode}\n    },` : ''}
  },
  (params) => {
    // Script step — migrated business logic
    wfa.actionStep(
      { $id: Now.ID['${internalName}_script'], label: ${JSON.stringify(name)} },
      \`${scriptEscaped}\`
    );
  }
);
`);
  }

  // ─── Trigger generation ───────────────────────────────────────────────────

  _buildTrigger(flowStructure, snTableName) {
    const raw  = (flowStructure.type ?? '').toLowerCase();
    const trig = flowStructure.trigger ?? {};

    if (raw.includes('record') || raw === 'record') {
      const when  = trig.when ?? trig.triggerType ?? 'createdOrUpdated';
      const snWhen = { created: 'created', updated: 'updated', 'createdorupdated': 'createdOrUpdated',
                       before: 'updated', after: 'updated' }[when.toLowerCase()] ?? 'createdOrUpdated';
      const conditionStr = trig.condition ?? trig.encodedQuery ?? '';
      return `wfa.trigger(trigger.record.${snWhen}, {
      $id: Now.ID['trigger'],
      table: ${JSON.stringify(snTableName ?? 'incident')},${conditionStr ? `\n      condition: ${JSON.stringify(conditionStr)},` : ''}
    })`;
    }

    if (raw.includes('scheduled') || raw === 'scheduled') {
      const freq = (trig.runType ?? trig.frequency ?? 'daily').toLowerCase();
      const snFreq = { daily: 'daily', weekly: 'weekly', monthly: 'monthly',
                       periodically: 'repeat', once: 'runOnce' }[freq] ?? 'daily';
      return `wfa.trigger(trigger.scheduled.${snFreq}, {
      $id: Now.ID['trigger'],
      time: '08:00:00', // TODO: set correct run time
    })`;
    }

    if (raw.includes('catalog')) {
      return `wfa.trigger(trigger.serviceCatalog, {
      $id: Now.ID['trigger'],
    })`;
    }

    if (raw.includes('email')) {
      return `wfa.trigger(trigger.inboundEmail, {
      $id: Now.ID['trigger'],
    })`;
    }

    // on_demand / manual — use service catalog or leave as comment
    return `/* on-demand: no trigger — convert to subflow or add a service catalog trigger */
    wfa.trigger(trigger.serviceCatalog, { $id: Now.ID['trigger'] })`;
  }

  // ─── Body / step generation ───────────────────────────────────────────────

  _buildBody(elements, fieldMappings, snTableName, context) {
    const lines = [];
    let stepIdx = 1;

    for (const el of elements) {
      const id    = this._toId(el.name ?? el.label ?? `step_${stepIdx}`);
      const label = el.label ?? el.name ?? `Step ${stepIdx}`;
      lines.push(this._buildStep(el, id, label, fieldMappings, snTableName, context, stepIdx));
      stepIdx++;
    }

    return lines.filter(Boolean).join('\n\n');
  }

  _buildStep(el, id, label, fieldMappings, snTableName, context, idx) {
    const kind = el.kind ?? '';
    const ind  = '    '; // 4 spaces inside body function

    // ── Decision / IF block ──
    if (kind === 'decision' || kind === 'condition') {
      const conditions = el.conditions ?? el.rules ?? [];
      const condExpr   = conditions.length
        ? conditions.map(c => {
            const f   = fieldMappings[c.leftValueReference ?? c.field] ?? c.leftValueReference ?? c.field ?? '';
            const op  = this._mapConditionOp(c.operator ?? 'EqualTo');
            const val = c.rightValue?.stringValue ?? c.value ?? '';
            return `\${wfa.dataPill(params.trigger?.Record?.${f}, 'string')}${op}${val}`;
          }).join('^')
        : `// TODO: add condition for "${label}"`;
      return [
        `${ind}// IF: ${label}`,
        `${ind}wfa.flowLogic.if(`,
        `${ind}  { $id: Now.ID['${id}'], condition: \`${condExpr}\` },`,
        `${ind}  () => {`,
        `${ind}    // TODO: add steps for the true branch`,
        `${ind}  }`,
        `${ind});`,
      ].join('\n');
    }

    // ── For Each loop ──
    if (kind === 'loop') {
      const collection = el.collectionReference ?? 'records';
      return [
        `${ind}// FOR EACH: ${label}`,
        `${ind}wfa.flowLogic.forEach(`,
        `${ind}  { $id: Now.ID['${id}'] },`,
        `${ind}  wfa.dataPill(params.flowVariables?.${collection}, 'array'), // TODO: set correct collection`,
        `${ind}  (item) => {`,
        `${ind}    // TODO: add loop body steps`,
        `${ind}  }`,
        `${ind});`,
      ].join('\n');
    }

    // ── Create Record ──
    if (kind === 'recordCreate') {
      const fields = this._buildFields(el.inputAssignments ?? [], fieldMappings);
      return [
        `${ind}// Create ${snTableName ?? 'record'}`,
        `${ind}const created_${idx} = wfa.action(action.core.createRecord, { $id: Now.ID['${id}'], label: ${JSON.stringify(label)} }, {`,
        `${ind}  table_name: ${JSON.stringify(snTableName ?? 'incident')},`,
        `${ind}  ${fields || '// TODO: add field values'},`,
        `${ind}});`,
      ].join('\n');
    }

    // ── Update Record ──
    if (kind === 'recordUpdate') {
      const fields = this._buildFields(el.inputAssignments ?? [], fieldMappings);
      return [
        `${ind}// Update ${snTableName ?? 'record'}`,
        `${ind}const updated_${idx} = wfa.action(action.core.updateRecord, { $id: Now.ID['${id}'], label: ${JSON.stringify(label)} }, {`,
        `${ind}  table_name: ${JSON.stringify(snTableName ?? 'incident')},`,
        `${ind}  sys_id: wfa.dataPill(params.trigger?.Record?.sys_id, 'string'),`,
        `${ind}  ${fields || '// TODO: add field values'},`,
        `${ind}});`,
      ].join('\n');
    }

    // ── Delete Record ──
    if (kind === 'recordDelete') {
      return [
        `${ind}// Delete record`,
        `${ind}wfa.action(action.core.deleteRecord, { $id: Now.ID['${id}'], label: ${JSON.stringify(label)} }, {`,
        `${ind}  table_name: ${JSON.stringify(snTableName ?? 'incident')},`,
        `${ind}  sys_id: wfa.dataPill(params.trigger?.Record?.sys_id, 'string'), // TODO: verify sys_id reference`,
        `${ind}});`,
      ].join('\n');
    }

    // ── Look Up Record ──
    if (kind === 'recordLookup') {
      const conditions = (el.filterConditions ?? []).map(c => {
        const f  = fieldMappings[c.field ?? ''] ?? c.field ?? '';
        const v  = c.value ?? '';
        return `${f}=${v}`;
      }).join('^') || '// TODO: add query conditions';
      return [
        `${ind}// Look up ${snTableName ?? 'record'}`,
        `${ind}const lookup_${idx} = wfa.action(action.core.lookUpRecord, { $id: Now.ID['${id}'], label: ${JSON.stringify(label)} }, {`,
        `${ind}  table_name: ${JSON.stringify(snTableName ?? 'incident')},`,
        `${ind}  conditions: \`${conditions}\`,`,
        `${ind}});`,
      ].join('\n');
    }

    // ── Subflow call ──
    if (kind === 'subflow') {
      const subflowRef = el.subflowName ?? el.flowName ?? 'importedSubflow';
      const subflowId  = this._toId(subflowRef);
      const inputArgs  = (el.inputAssignments ?? []).map(p => {
        const snField = fieldMappings[p.field ?? p.name] ?? p.field ?? p.name;
        return `${ind}    ${snField}: wfa.dataPill(/* ${p.value ?? 'TODO'} */, 'string'),`;
      }).join('\n') || `${ind}    // TODO: pass subflow input values`;
      return [
        `${ind}// Call subflow: ${label}`,
        `${ind}// Import the subflow: import { ${subflowId} } from './${subflowId}';`,
        `${ind}const subflow_${idx} = wfa.subflow(`,
        `${ind}  ${subflowId},`,
        `${ind}  { $id: Now.ID['${id}'] },`,
        `${ind}  {`,
        inputArgs,
        `${ind}    waitForCompletion: true,`,
        `${ind}  }`,
        `${ind});`,
      ].join('\n');
    }

    // ── Send Notification ──
    if (kind === 'action' && (el.raw_type ?? '').toLowerCase().includes('email')) {
      return [
        `${ind}// Send notification: ${label}`,
        `${ind}wfa.action(action.core.sendNotification, { $id: Now.ID['${id}'], label: ${JSON.stringify(label)} }, {`,
        `${ind}  // TODO: configure notification`,
        `${ind}});`,
      ].join('\n');
    }

    // ── Generic assignment / script step ──
    const configDump = el.config
      ? Object.entries(el.config).slice(0, 5).map(([k, v]) => `//   ${k}: ${JSON.stringify(v)}`).join('\n' + ind)
      : '';
    const scriptBody = el._overrideScript ?? (
      el.kind === 'assignment'
        ? (el.assignmentItems ?? []).map(i => {
            const f = fieldMappings[i.assignToReference] ?? i.assignToReference;
            const v = i.value?.stringValue ?? i.value?.elementReference ?? i.value ?? 'TODO';
            return `current.${f} = ${JSON.stringify(String(v))};`;
          }).join('\n          ') + '\ncurrent.update();'
        : `// TODO: implement "${label}"\n          // Type: ${kind}${configDump ? '\n          ' + configDump : ''}`
    );

    return [
      `${ind}// ${label}`,
      `${ind}wfa.action(action.core.script, { $id: Now.ID['${id}'], label: ${JSON.stringify(label)} }, {`,
      `${ind}  script: \``,
      `${ind}    ${scriptBody.split('\n').join('\n          ')}`,
      `${ind}  \`,`,
      `${ind}});`,
    ].join('\n');
  }

  // ─── Helpers ──────────────────────────────────────────────────────────────

  _buildInputOutputSchema(vars) {
    return vars.map(v => {
      const type = this._mapVarTypeToColumn(v.dataType ?? v.type ?? 'String');
      return `      ${this._toId(v.name)}: ${type}({ label: ${JSON.stringify(v.label ?? v.name)}, mandatory: ${v.mandatory ? 'true' : 'false'} }),`;
    }).join('\n');
  }

  _buildFlowVariables(vars) {
    const internal = vars.filter(v => !v.isInput && !v.isOutput);
    return internal.map(v => {
      const type = this._mapVarTypeToColumn(v.dataType ?? v.type ?? 'String');
      return `      ${this._toId(v.name)}: ${type}({ label: ${JSON.stringify(v.label ?? v.name)} }),`;
    }).join('\n');
  }

  _buildFields(assignments, fieldMappings) {
    if (!assignments.length) return null;
    return 'fields: {\n' + assignments.map(p => {
      const f = fieldMappings[p.field ?? p.name] ?? p.field ?? p.name;
      const v = p.value ?? '';
      return `      ${f}: ${JSON.stringify(String(v))},`;
    }).join('\n') + '\n    }';
  }

  _mapVarTypeToColumn(sfType) {
    const map = {
      String: 'StringColumn', Text: 'StringColumn', string: 'StringColumn',
      Number: 'IntegerColumn', Integer: 'IntegerColumn', integer: 'IntegerColumn',
      Boolean: 'BooleanColumn', boolean: 'BooleanColumn',
      Date: 'DateTimeColumn', DateTime: 'DateTimeColumn',
      Reference: 'ReferenceColumn', SObject: 'ReferenceColumn',
    };
    return map[sfType] ?? 'StringColumn';
  }

  _mapConditionOp(sfOp) {
    const map = {
      EqualTo: '=', NotEqualTo: '!=', GreaterThan: '>', GreaterThanOrEqualTo: '>=',
      LessThan: '<', LessThanOrEqualTo: '<=', Contains: 'CONTAINS',
      StartsWith: 'STARTSWITH', IsNull: 'ISEMPTY', IsNotNull: 'ISNOTEMPTY',
    };
    return map[sfOp] ?? '=';
  }

  _toId(name) {
    return (name ?? 'unnamed').toLowerCase().replace(/[^a-z0-9]/g, '_').replace(/^_+|_+$/g, '');
  }

  _isSubflow(flowStructure) {
    const t = (flowStructure.type ?? '').toLowerCase();
    return t === 'subflow' || t === 'autolaunchedflow' || flowStructure.isSubflow === true;
  }

  _wrap(code) {
    return code.trim();
  }
}
